# Local Development Properties
# Database Configuration
# Defaults to localhost for running directly on your machine. 
# Docker Compose will override this to 'postgres'.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:battlegrounds}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.turf.battlegrounds=DEBUG
logging.file.name=logs/app.log

# Actuator
management.endpoints.web.exposure.include=*

# Liquibase Configuration
spring.liquibase.change-log=file:src/main/resources/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
